services:
  vitae-vista:
    build:
      context: .
      dockerfile: VitaeVista/Dockerfile
    ports:
      - "5001:8080"
    environment:
      - DOTNET_ENVIRONMENT=Development
      - DOTNET_USE_POLLING_FILE_WATCHER=1
    depends_on:
      - fastapi-service

  fastapi-service:
    build:
      context: ./fastapi-service
      dockerfile: Dockerfile
    ports:
      - "8001:8001"