services:
  vitae-vista-api:
    build:
      context: .
      dockerfile: VitaeVista.API/Dockerfile
    ports:
      - 5002:8081
    environment:
      - ASPNETCORE_URLS=http://+:8081
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081"]
      interval: 10s
      retries: 5
      start_period: 5s
    networks:
      - vitae-network

  fastapi-service:
    build:
      context: ./fastapi-service
      dockerfile: Dockerfile
    ports:
      - 8001:8001
    networks:
      - vitae-network

  vitaevista-frontend:
    build:
      context: ./vitaevista-frontend  # Make sure this is correct
      dockerfile: Dockerfile  # This should match exactly
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
    depends_on:
      - vitae-vista-api
    networks:
      - vitae-network

networks:
  vitae-network:
    driver: bridge
